//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelecomNevaSvyaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int id_employee { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public int id_role { get; set; }
        public string nomer { get; set; }
        public string password { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
